# Generated by Django 5.2.1 on 2025-08-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletinPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('archivo_pdf', models.FileField(upload_to='boletines/')),
            ],
        ),
    ]
